let game=new Chess(),board=null,mode="human",orientation="white",searching=false,andro=null,sf=null;
const $=s=>document.querySelector(s);
function render(){board.position(game.fen());$("#fen").textContent=game.fen();$("#moveList").innerHTML="";game.history().forEach(m=>{let li=document.createElement("li");li.textContent=m;$("#moveList").appendChild(li)});$("#status").textContent=game.game_over()?(game.in_checkmate()?"Checkmate":"Game over"):"Ready";$("#thinking").textContent=searching?"Thinking…":"Ready"}
function boardCfg(){return{draggable:true,position:game.fen(),orientation:orientation,pieceTheme:"https://cdn.jsdelivr.net/npm/chessboardjs@1.0.0/www/img/chesspieces/wikipedia/{piece}.png",onDragStart:(s)=>{if(searching)return false;if(mode==="human"&&game.turn()!=="w")return false;return true},onDrop:(from,to)=>{let m=game.move({from:from,to:to,promotion:"q"});if(!m)return"snapback";render();if(mode==="human"&&!game.game_over())setTimeout(andromedaTurn,80)},onSnapEnd:()=>board.position(game.fen())}}
async function loadAndromeda(){try{let m=await import("../dist/andromeda.js");andro=await m.default();setStatus("Andromeda WASM loaded")}catch(e){console.error(e);setStatus("Andromeda WASM unavailable")}}
function setStatus(s){$("#status").textContent=s}
function aSend(c){if(!andro)return"";try{let e=andro.createAndromedaEngine();return e.uci(c)}catch(e){console.error(e);return""}}
function parse(line){let d=line.match(/depth (\d+)/),n=line.match(/nodes (\d+)/),p=line.match(/nps (\d+)/),s=line.match(/score (cp|mate) (-?\d+)/);if(d)$("#depth").textContent=d[1];if(n)$("#nodes").textContent=Number(n[1]).toLocaleString();if(p)$("#nps").textContent=Number(p[1]).toLocaleString();if(s){let v=s[1]==="mate"?(+s[2]>0?99:-99):+s[2]/100;$("#score").textContent=s[1]==="mate"?"M"+s[2]:(v>=0?"+":"")+v.toFixed(2);$("#evalbar").style.width=Math.max(3,Math.min(97,50+v*9))+"%"}}
function andromedaTurn(){if(searching||game.game_over()||!andro)return;searching=true;render();let out=aSend("position fen "+game.fen());out=aSend("go movetime "+$("#time").value);parse(out);let bm=out.match(/bestmove ([a-h][1-8][a-h][1-8][qrbn]?)/);if(bm){game.move({from:bm[1].slice(0,2),to:bm[1].slice(2,4),promotion:bm[1][4]||"q"})}searching=false;render()}
function start(){game.reset();searching=false;render();if(mode==="engine")setTimeout(stockfishTurn,250)}
function stockfishTurn(){if(searching||game.game_over()||!sf)return;searching=true;render();sf.postMessage("position fen "+game.fen());sf.postMessage("go movetime "+$("#time").value)}
function initSF(){try{sf=new Worker("./stockfish-worker.js");sf.onmessage=e=>{let l=String(e.data);parse(l);let bm=l.match(/bestmove ([a-h][1-8][a-h][1-8][qrbn]?)/);if(bm){game.move({from:bm[1].slice(0,2),to:bm[1].slice(2,4),promotion:bm[1][4]||"q"});searching=false;render();if(mode==="engine")setTimeout(andromedaTurn,150)}};sf.postMessage("uci");sf.postMessage("isready")}catch(e){setStatus("Stockfish worker unavailable")}}
document.querySelectorAll(".mode").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll(".mode").forEach(x=>x.classList.toggle("active",x===b));$("#blackName").textContent=mode==="engine"?"Stockfish 18":"Andromeda";$("#whiteName").textContent=mode==="engine"?"Andromeda":"You";start()});
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#analysis").classList.toggle("hidden",b.dataset.tab!=="analysis");$("#moves").classList.toggle("hidden",b.dataset.tab!=="moves")});
$("#new").onclick=start;$("#flip").onclick=()=>{orientation=orientation==="white"?"black":"white";board.orientation(orientation)};$("#undo").onclick=()=>{if(!searching){game.undo();if(mode==="human")game.undo();render()}};$("#stop").onclick=()=>{if(sf)sf.postMessage("stop");searching=false;render()};
board=Chessboard("board",boardCfg());render();loadAndromeda();initSF();